### PR TITLE
Refactor to use simpl@simpl.world user.

### PR DESCRIPTION
**Pull request by janeeisenstein**
Refactor SIMPL_GAMES_AUTH to match latest simple-games.api.

### CODE REVIEW

**Comment by jefftriplett** [comment]
Should this change be made to the docs in the simpl.world website too? 

For example: https://github.com/simplworld/simpl.world.website/blob/master/_docs/tutorials/modelservice.md 

I remember pre-breaking you mentioning that there were some out-of-date references but I saw this on my GitHub stream and I wanted to say something sooner than later.

**Comment by janeeisenstein** [comment]
Not yet. This change is just to keep this repo up to date with the other simpl repos, which are not yet public. 

The  current simpl.world docs need top down restructuring, updating and editing. It's content can draw from this repo when that happens.

**Comment by frankwiles** [comment]
But @janeeisenstein the docs are ultimately going to live in the website repo and not this repo so changes here are likely gonna get lost is what I think @jefftriplett is saying.

**Comment by janeeisenstein** [comment]
True @frankwiles, but this repo is correct and consistent. The simpl.world docs are in bad shape and need top-down reworking.  This repo can provide content for that effort and then go away.

**Pull request merged**
